version: '3'
services:

  db:
    image: postgres
    env_file:
      - .db.test.env
    networks:
      - db_nw
  backend:
    env_file:
      - .backend.test.env
      - .db.test.env
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - db_nw
    ports:
      - "5000:5000"
    entrypoint:
      - ./boot.test.sh
        #    command: flask run --host=0.0.0.0

networks:
  db_nw:
    driver: bridge

