version: '3'
services:

  db:
    image: postgres
    env_file:
      - .db.dev.env
    volumes:
      - ./data-dev:/var/lib/postgresql/data
    networks:
      - db_nw
  backend:
    env_file:
      - .backend.dev.env
      - .db.dev.env
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - db_nw
    ports:
      - "5000:5000"
    entrypoint:
      - ./boot.dev.sh

networks:
  db_nw:
    driver: bridge
